kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "hello-worldb3"
  labels:
    nirmata.io/deployment.name: "hello-worldb3"
    nirmata.io/application.name: "hello-worldb3"
    nirmata.io/component: "hello-worldb3"
    damien: "test1"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/application.name: "hello-worldb3"
      nirmata.io/component: "hello-worldb3"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {
        test: "test",
        aaa: "bbb",
        ccc: "ddd"
      }
      labels:
        nirmata.io/deployment.name: "hello-worldb3"
        nirmata.io/application.name: "hello-worldb3"
        nirmata.io/component: "hello-worldb3"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "hello-worldb3"
        image: "busybox"
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        imagePullPolicy: "Always"
