apiVersion: v1
kind: Pod
metadata:
  annotations:
    aaa: bbb
  labels:
    app.kubernetes.io/instance: helloworld1
  name: busybox
  namespace: helloworld1
spec:
  containers:
  - image: busybox
    name: hello-world-busybox
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
